export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LIBRARY_PATH

export INSTALL_PATH=~/gcc-4.5.1/install
export PATH=${INSTALL_PATH}/bin:$PATH
export export LD_LIBRARY_PATH=${INSTALL_PATH}/lib64
export export LD_RUN_PATH=${INSTALL_PATH}/lib64

export CUDA_INSTALL_PATH=/usr/local/cuda
export CUDAHOME=$CUDA_INSTALL_PATH
export LD_LIBRARY_PATH=$CUDA_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_INSTALL_PATH/lib:$LD_LIBRARY_PATH
export PATH=$CUDA_INSTALL_PATH/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_INSTALL_PATH/include:$LD_LIBRARY_PATH
export PATH=$CUDA_INSTALL_PATH/include:$PATH
export NVIDIA_CUDA_SDK_LOCATION=/root/NVIDIA_GPU_Computing_SDK
export NVIDIA_COMPUTE_SDK_LOCATION=$NVIDIA_CUDA_SDK_LOCATION
